### ISSUE TITLE
Error when opening webcam

### ISSUE THREAD

**Issue by PrashantSaikia** [abishekvashok/RepCounter#3]
I keep getting this error:

```
Traceback (most recent call last):
  File "run.py", line 128, in <module>
    main()
  File "run.py", line 81, in main
    input_image, display_image, output_scale = posenet.read_cap(
  File "/Users/username/Downloads/Rep-Counter/posenet/utils.py", line 28, in read_cap
    raise IOError("webcam failure")
OSError: webcam failure
```

Any idea why, and how to fix it? Thanks!

**Comment by abishekvashok** [comment]
Hey are you sure that a webcam is connected?
